<div id="rightside">
	<h1>Dorsey&rsquo;s projects</h1>
	<h2>Facebook wasn&rsquo;t enough</h2>
	<p>The programming framework that I developed for building this site
		came out of a project I did for a local construction company
		in exchange for work on a home improvement project.  While Facebook
		allows you to upload, comment on, and tag photos, and create fan pages, that wasn&rsquo;t
		what the company owner wanted as a way to present his project
		portfolio to prospective clients.</p>
	<p>Instead, he wanted an online brochure to which he could refer
		potential clients, and that he could maintain without me using a simple admin facility.
		The site had to support unlimited numbers of projects and photos of different sizes,
		as well as project and photo captions.  We also wanted those captions to be searchable as
		the online portfolio grew.</p>
	<h2>Bartering my services</h2>
	<p>This site is an example of that framework using projects that I&rsquo;ve
		worked on over many years. I&rsquo;m using to show friends some of the things I&rsquo;ve
		done for two reasons:  First, I&rsquo;m proud of my projects.  Second, I am
		happy to barter my technical services for other&rsquo;s services or tangible
		objects.</p>
	<p>I hope that it&rsquo;s obvious that anyone wanting a vanity site of their own, or
		has a business that can use this kind of project presentation
		will think about this.  I value a website with this kind of capability between $1,500 to $3,000,
		and will consider any bartering arrangement of similar value. I&rsquo;m especially interested in
		trading time for machine tools.</p>
	<h2>Before you go</h2>
	<p>Please take a look at my project gallery.</p>
</div>