<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<base href="<?=__PUBLIC_PATH?>/" />
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<title><?=$title?></title>
	<script type="text/javascript">
		var public_path = '<?=__PUBLIC_PATH?>';
		var updateserver = '<?=__PUBLIC_PATH?>/servers/updateproject.php';
		var queryserver = '<?=__PUBLIC_PATH?>/servers/queryprojects.php';
	</script>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
	<?=$links?>
	<!--[if lte IE 8]>
	<style type="text/css" media="all">
	@import "css/styleie.css";
	</style>
	<![endif]-->
	<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div id="container">
	<div id="header">
		<img src="images/dorseyharrington.jpg" alt="Log out of admin pages" />
		<a href="<?=__PUBLIC_PATH.'/account/logout'?>"><span style="position: absolute; right: 10px; top: 1px; font-size: 10px;">logout</span></a>
	</div>
	<div id="account">
		<?=$menu?>
		<?=$content?>
	</div>
</div>
</body>
</html>