<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtms" xmlns:fb="http://ogp.me/ns/fb#">
<head>
	<base href="<?=__PUBLIC_PATH?>/" />
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
<?php if( isset( $fbAdmins ) ) { ?>
	<meta property="og:title" content="<?=$fbPageTitle?>" />
	<meta property="og:type" content="activity:author" />
	<meta property="og:url" content="<?=__PUBLIC_PATH?>/project/fullgallery" />
	<meta property="og:image" content="" />
	<meta property="og:site_name" content="<?=$fbPageContent?>" />
	<meta property="og:admins" content="<?=$fbAdmins?>" />
<?php } ?>
	<title><?=$title?></title>
	<script type="text/javascript">
		var public_path = '<?=__PUBLIC_PATH?>';
		var updateserver = '<?=__PUBLIC_PATH?>/servers/updateproject.php';
		var queryserver = '<?=__PUBLIC_PATH?>/servers/queryprojects.php';
	</script>
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js"></script>
	<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
	<?=$links?>
	<!--[if lte IE 8]>
	<style type="text/css" media="all">
	@import "css/styleie.css";
	</style>
	<![endif]-->
	<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div id="container">
	<div id="header">
		<a href="<?=__PUBLIC_PATH?>"><img src="images/<?=$config->config_values['images']['header_image']?>" alt="<?=$config->config_values['mail']['admin_name']?> home page"/></a>
		<div id="logout"><?=$logout?></div>
	</div>
	<div id="content">
		<?=$menu?>
		<?=$sidebarimage?>
		<?=$content?>
	</div>
	<div id="footer">
		<ul><li><span class="footernumbers">&copy;2011</span>&nbsp;<?=$config->config_values['mail']['admin_name']?></li>
			<li><?=$config->config_values['mail']['admin_city']?></li>
			<li><a href="mailto:<?=$config->config_values['mail']['admin_email']?>"><?=$config->config_values['mail']['admin_email']?></a></li>
		</ul>
	</div>
</div>
</body>
</html>