<div id="rightside" style="padding-top: 50px;">
	<blockquote>
		<p style="margin-top: 0px;">Lindex Construction Company prides itself on customer service.
		In an effort to make your construction experience as rewarding and
		stress-free as possible, we offer our shopping list to guide you through the
		process of selecting the fixtures that best suit your needs and personal style.</p>
		<p>Download yours by clicking the logo below:</p>
	</blockquote>
	<div class="lowerblock">
		<img src="images/LCC_Website_Shop_Logos.png" alt="Reference logos" />
	</div>
</div>