<style>
	table {border-collapse: collapse;}
	td, th {font-family: arial, san-serif; font-size: 10px;}
	th {font-size: 11px;}
</style>
<table border="0" cellpadding="5px" cellspacing="0">
	<tr><th colspan="3" align="left"><a href='<?=$link?>' target="_parent"><?=$title?></a></th></tr>
	<tr><td valign="top"><img src="<?=$mainBeforeImageThumb?>" /></td><td valign="top"><img src="<?=$mainAfterImageThumb?>" /></td><td valign="top" width="180"><?=$description?></td></tr>
</table>